#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 26 15:35:37 WET 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_ps2_keyboard_behav -key {Behavioral:sim_1:Functional:tb_ps2_keyboard} -tclbatch tb_ps2_keyboard.tcl -view /home/teixeira/PS2_Keyboard_V2/PS2_Keyboard/tb_ps2_keyboard_behav.wcfg -log simulate.log"
xsim tb_ps2_keyboard_behav -key {Behavioral:sim_1:Functional:tb_ps2_keyboard} -tclbatch tb_ps2_keyboard.tcl -view /home/teixeira/PS2_Keyboard_V2/PS2_Keyboard/tb_ps2_keyboard_behav.wcfg -log simulate.log

